//
//  CPPMetalDataType.cpp
//  vox.render
//
//  Created by 杨丰 on 2022/1/12.
//

#include "CPPMetalDataType.hpp"
#include "CPPMetalImplementation.hpp"
#include "CPPMetalInternalMacros.h"
#include <Metal/Metal.h>

using namespace MTL;

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeNone);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeStruct);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeArray);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat2x2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat2x3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat2x4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat3x2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat3x3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat3x4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat4x2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat4x3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeFloat4x4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf2x2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf2x3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf2x4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf3x2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf3x3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf3x4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf4x2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf4x3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeHalf4x4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeInt);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeInt2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeInt3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeInt4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUInt);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUInt2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUInt3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUInt4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeShort);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeShort2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeShort3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeShort4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUShort);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUShort2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUShort3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUShort4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeChar);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeChar2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeChar3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeChar4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUChar);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUChar2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUChar3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeUChar4);

CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeBool);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeBool2);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeBool3);
CPP_METAL_VALIDATE_ENUM_ALIAS(DataTypeBool4);
